---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-deployment
spec:
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
      ver: 2.4.0
    
  template:
    metadata:
      labels:
        app: openmrs
        ver: 2.4.0
    spec:
      containers:
        - image: 982942610675.dkr.ecr.us-west-2.amazonaws.com/mydockerrepo:latest
          name: openmrs
          ports:
            - containerPort: 8080
              protocol: TCP